chouette_coop_admin:
    resource: "@ChouetteCoopAdminBundle/Resources/config/routing.yml"
    prefix:   /

glukose_contact:
    resource: "@GlukoseContactBundle/Resources/config/routing.yml"
    prefix:   /
    
glukose_user:
    resource: "@GlukoseUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin