sonata_admin:
    title: 'Admin chouettos'

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: right }
            - { type: sonata.block.service.text, position: left, settings: { content: "<h2>Bienvenue dans Admin Chouettos !</h2>

                                                                                 <h3>Admin Chouettos est l’annuaire des Chouettos.</h3>
                                                                                 <p>
                                                                                 Il permet d’autoriser l’accès aux outils de La Chouette Coop (passage en caisse, espace membres, …) à un·e Chouettos.
                                                                                 </p>
                                                                                 <p>
                                                                                 Pour celà : sa fiche doit être créée dans Admin Chouettos,
                                                                                 <strong>ET</strong> sa fiche doit être activée (en cochant la case « Membre ? »).
                                                                                 </p>
                                                                                 <p>
                                                                                 Admin Chouettos permet également de stocker les données recueillies pour chaque Chouettos ou personne
                                                                                 s'étant déclarée intéréssée par le projet (lors d'une réunion d'acceuil par exemple).
                                                                                 </p>

                                                                                 <h3>Quand et pour quelle opération utiliser Admin Chouettos ?</h3>
                                                                                 <ul>
                                                                                 <li>
                                                                                 Lors d’une nouvelle adhésion :
                                                                                 création de la fiche du Chouettos (nouvel adhérent)
                                                                                 </li>
                                                                                 <li>
                                                                                 Lors d’un renouvellement d’adhésion :
                                                                                 ajout d’une adhésion sur la fiche et modifications éventuelles de certaines données (ex: adresse)
                                                                                 </li>
                                                                                 <li>
                                                                                 Lorsqu’on recueille de nouvelles informations sur un Chouettos (date de naissance, nouvelle adresse...) :
                                                                                 modification de la fiche
                                                                                 </li>
                                                                                 <li>
                                                                                 Lorsqu’une adhésion devient effective (adhésion à l’année en cours faite en fin d’année précédente) :
                                                                                 activation de la fiche
                                                                                 </li>
                                                                                 </ul>"} }
    templates:
        layout:               'standard_layout.html.twig'
    options:
        legacy_twig_text_extension: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
