# Big thanks to https://github.com/yemiwebby/symfony-docker-tut

version: '3.8'
services:
  database:
    image: mariadb:10.3
    ports:
    - '3306:3306'
    environment:
    - MARIADB_ROOT_PASSWORD=adminchouettos
    - MYSQL_DATABASE=adminchouettos
    - MARIADB_USER=adminchouettos
    - MARIADB_PASSWORD=adminchouettos
    volumes:
    - ./data/:/var/lib/mysql
    # To init :
    # mysql -p
    # To grant access from php
    # CREATE USER 'adminchouettos'@'php' IDENTIFIED BY 'adminchouettos';
    # GRANT ALL ON adminchouettos.* TO 'adminchouettos'@'php';
    # To grant access from symfony
    # CREATE USER 'adminchouettos'@'symfony' IDENTIFIED BY 'adminchouettos';
    # GRANT ALL ON adminchouettos.* TO 'adminchouettos'@'symfony';
    # To be able to run `mysql -u adminchouettos -p adminchouettos` in database
    # CREATE USER 'adminchouettos'@'localhost' IDENTIFIED BY 'adminchouettos';
    # GRANT ALL ON adminchouettos.* TO 'adminchouettos'@'localhost';
  symfony:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/app/adminchouettos'
    environment:
      - SYMFONY_PROJECT_NAME=adminchouettos
      - MARIADB_HOST=database
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=adminchouettos
      - MARIADB_PASSWORD=adminchouettos
      - MARIADB_DATABASE=adminchouettos
    depends_on:
      - database
