parameters:
    glukose_user.component.authentication.handler.login_success_handler.class: Glukose\UserBundle\Component\Authentication\Handler\LoginSuccessHandler

services:
    glukose_user.component.authentication.handler.login_success_handler:
        class:  %glukose_user.component.authentication.handler.login_success_handler.class%
        arguments:  [@router, @security.context, @session]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    app.form.registration:
        class: Glukose\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
            
    sonata.admin.utilisateur:
        class: Glukose\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des membres", label: "Utilisateurs", icon: %iconUser% }
        arguments:
            - ~
            - Glukose\UserBundle\Entity\User
            - GlukoseUserBundle:UserAdmin
        calls:
            - [ setTranslationDomain, [GlukoseAdminContactBundle]]
            - [ setLdapService, [@chouette.admin.ldap]]
            
    sonata.admin.groupes:
        class: Glukose\UserBundle\Admin\GroupeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des membres", label: "Groupes", icon: %iconUser% }
        arguments:
            - ~
            - Glukose\UserBundle\Entity\Groupe
            - ~
        calls:
            - [ setTranslationDomain, [GlukoseAdminContactBundle]]
            - [ setLdapService, [@chouette.admin.ldap]]
            
    sonata.admin.adhesion:
        class: Glukose\UserBundle\Admin\AdhesionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des membres", label: "Adhesions", icon: %iconUser%, show_in_dashboard: true }
        arguments:
            - ~
            - Glukose\UserBundle\Entity\Adhesion
            - ~
        calls:
            - [ setTranslationDomain, [GlukoseAdminContactBundle]]