services:
    sonata.admin.adresse:
        class: Glukose\ContactBundle\Admin\AdresseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des membres", label: "Adresse", icon: %iconUser% }
        arguments:
            - ~
            - Glukose\ContactBundle\Entity\Adresse
            - ~
        calls:
            - [ setTranslationDomain, [GlukoseContactBundle]]
