chouette_coop_admin_homepage:
    path:     /
    defaults: { _controller: ChouetteCoopAdminBundle:Main:index }

chouette_coop_admin_export_gh:
    path:     /api/export/gh
    defaults: { _controller: ChouetteCoopAdminBundle:Main:exportGHCodeBarre }

chouette_coop_admin_import_membres:
    path:     admin/import-membres
    defaults: { _controller: ChouetteCoopAdminBundle:Import:importMembres }

chouette_coop_desactivation:
    path:     admin/desactivation/{annee}
    defaults: { _controller: ChouetteCoopAdminBundle:Import:desactivationMembres }

chouette_coop_codebare:
    path:     admin/codebarre/{annee}
    defaults: { _controller: ChouetteCoopAdminBundle:Import:creationDeCodeBarre }

chouette_coop_updateuser:
    path:     admin/updata/users
    defaults: { _controller: ChouetteCoopAdminBundle:Import:updateAllUsers }

chouette_coop_admin_ldap_membres:
    path:     admin/ldap-membres
    defaults: { _controller: ChouetteCoopAdminBundle:Import:ldapMembres }

chouette_coop_admin_weekly:
    path:     zduJNFHI4e54qzd5/weeklymail/{boolSend}
    defaults: { _controller: ChouetteCoopAdminBundle:Import:weeklyNewMembers, boolSend:'1'  }
