chouette_coop_admin_homepage:
    path:     /
    defaults: { _controller: ChouetteCoopAdminBundle:Main:index }

chouette_coop_admin_import_membres:
    path:     /import-membres
    defaults: { _controller: ChouetteCoopAdminBundle:Import:importMembres }

chouette_coop_desactivation:
    path:     admin/desactivation/{annee}
    defaults: { _controller: ChouetteCoopAdminBundle:Import:desactivationMembres }

chouette_coop_codebare:
    path:     admin/codebarre
    defaults: { _controller: ChouetteCoopAdminBundle:Import:creationDeCodeBarre }

chouette_coop_admin_ldap_membres:
    path:     /ldap-membres
    defaults: { _controller: ChouetteCoopAdminBundle:Import:ldapMembres }
